name: Build and Push Docker Image

on:
  repository_dispatch:
    types: [build-push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t "${{ inputs.repo_base_name }}/${{ inputs.repo_name }}:${{ github.sha }}" .

      - name: Tag Docker image with commit SHA
        run: docker tag "${{ inputs.repo_base_name }}/${{ inputs.repo_name }}:${{ github.sha }}" "${{ inputs.repo_base_name }}/${{ inputs.repo_name }}:${{ github.sha }}"

      - name: Push Docker images
        run: |
          docker push "${{ inputs.repo_base_name }}/${{ inputs.repo_name }}:${{ github.sha }}"

  workflow_calls:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Trigger stage or production build
        if: github.event.client_payload.repo_name
        uses: ./.github/workflows/${{ github.event.client_payload.repo_name }}.yml
        with:
          repo_base_name: mishikabatra
          repo_name: ${{ github.event.client_payload.repo_name }}
          branch_name: ${{ github.event.client_payload.branch_name }}
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
