name: Deploy to Production

on:
  push:
    branches:
      - production 

jobs:
  deploy:
    steps:
      - name: Trigger build and push to Docker Hub
        uses: ./.github/workflows/build_image.yml
        with:
          repo_name: production
          repo_base_name: mishikabatra
          branch_name: production
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
