name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  trigger-build:
    uses: ./.github/workflows/build_image.yml
    with:
      repo_base_name: mishikabatra
      repo_name: production
      branch_name: production
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
