name: Deploy to Stage

on:
  push:
    branches:
      - stage

jobs:
  trigger-build:
    uses: ./.github/workflows/build_image.yml
    with:
      repo_base_name: mishikabatra
      repo_name: stage
      branch_name: stage
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
